### ISSUE TITLE
Problems need to be updated

### ISSUE THREAD

**Issue by bhi5hmaraj** [captn3m0/codechef#2]
Can you please update the problem set.

**Comment by captn3m0** [comment]
I might get around to it someday. Could you tell me what exactly are you using this for?

**Comment by bhi5hmaraj** [comment]
My internet connection is not that good , so It would be really helpful if
I could get the problem statement offline.

bhishma

**Comment by sbshah97** [comment]
If you could tell how to update the repository, I'd be willing to send across a Pull Request to update the repository!

**Comment by captn3m0** [comment]
@salman-bhai Some steps may be missing:

1. Visit https://www.codechef.com/problems/easy (and other category pages)
2. Run something like `copy($('.problemname a').toArray().map(function(x){return x.getAttribute('href')}))` in the javascript console to get the entire problem list
3. Store this list in URLs subdirectory
4. Run `wget --input-file` to download everything in `URLs/easy.txt` into the `PROBLEMS/EASY` directory.
5. Repeat 1-4 for other categories
6. Take a complete backup at this point
7. Run `strip.php` (and modify it if needed). This script strips out the header/footer and other useless elements to improve problem file size.

Commit and file PR :+1:

**Comment by sbshah97** [comment]
I'll try this and let you know what happens!

**Comment by captn3m0** [comment]
Let me know if you face any issues :+1:

**Comment by captn3m0** [comment]
@salman-bhai Thinking of tackling this. Did you make any progress that I could continue on?

**Comment by sbshah97** [comment]
Umm no not really. KInda got stuck and then didn't really move on!

**Comment by bhi5hmaraj** [comment]
I'm interested in fixing this issue . Can you please help me in getting started .

**Comment by captn3m0** [comment]
@bhi5hmaraj See [my comment](https://github.com/captn3m0/codechef/issues/2#issuecomment-286112504) above in this thread.

**Comment by captn3m0** [comment]
Working on this in #3, made some progress by shifting over the codechef API, except it seems to have rate-limiting and more checks in place.

**Comment by captn3m0** [comment]
Progress:

```
./vendor/bin/robo stats
➜  [school] Download Status: 112/112
➜  [easy] Download Status: 130/510
➜  [medium] Download Status: 136/535
➜  [hard] Download Status: 104/312
➜  [challenge] Download Status: 0/102
```

I'm going to be merging #3, since I took care to migrate old problems (so the new version has guaranteed more problems than there used to be)

**Comment by captn3m0** [comment]
Spent some more time only to realize that the codechef URL scheme is not consistent (no more rate limits). Haven't worked on challenge problems, but closing this for now:

```
./vendor/bin/robo  stats
➜  [school] Download Status: 112/112
➜  [easy] Download Status: 546/547
➜  [medium] Download Status: 546/546
➜  [hard] Download Status: 319/319
➜  [challenge] Download Status: 0/102
```
