### ISSUE TITLE
Markdown not rendered

### ISSUE THREAD

**Issue by bhi5hmaraj** [captn3m0/codechef#4]
In most of the problems some of the markdown elements are not rendering properly . For example in this [problem](https://captnemo.in/codechef/problems/school/BRACKETS.html) , the output and the constraints aren't rendered.
![image](https://cloud.githubusercontent.com/assets/9746401/25572560/eaac688a-2e59-11e7-8e38-51b08c05b8df.png)

**Comment by captn3m0** [comment]
Yes, this is a bug in the HTML->Markdown converter I'd picked. `<pre>` tags can contain `<b>` tags, but the converter decided to convert everything inside `<pre>` to htmlentities so it doesn't work.

I could force codechef HTML directly (but it adds too much cruft to my liking) as an alternative.
