### ISSUE TITLE
PDF Files

### ISSUE THREAD

**Issue by dufferzafar** [captn3m0/codechef#7]
Having a single PDF file for all the problems would be nice.

I'm thinking of giving [jekyll-pdf](https://github.com/abeMedia/jekyll-pdf) a shot. If that doesn't work out, I'll try pandoc on the markdowns. I've used pandoc before to convert [geeksforgeeks to PDF](https://github.com/dufferzafar/geeks-pdf/), so I'm sure that would work. 

If someone has any other way, please let me know.

**Comment by captn3m0** [comment]
Sounds like a good idea. The PDF on https://github.com/dufferzafar/geeks-pdf/ looks great.

I'm used to pandoc, so I'll go ahead and try that first. I'm not used to latex, but since your template looks so great, I'm going to steal that and see if I can use it.

Unrelated: I'm trying to do something similar for the [HN-Classics Project](http://jsomers.net/hn/) at https://git.captnemo.in/nemo/hn-classics, and comments are welcome (tech is jekyll/ruby/php/python so far for the download/cleanup/staticgen parts, might use pandoc there as well for the final book.

**Comment by dufferzafar** [comment]
I looked into jekyll-pdf. Couldn't install it because of some gem issue. But as it turns out it doesn't create a single PDF anyway. So I guess, we're on our own. 

If you're looking into Pandoc, I could look into using `wkhtmltopdf` directly on all URLs to get a PDF per problem, and then merging them all into one big PDF. I wonder what would happen to the document outline in that case.

Thanks for mentioning HN-Classics, I wasn't aware of it and it looks really cool. What criteria will you use to sort these articles? No. of votes or their `(year)`?

While we're talking about other projects, I wrote a script to [convert source code into PDF](https://github.com/dufferzafar/src2tex/) - which I read (and annotate) on my iPad. I'm trying it out with [Bitcoin's source](https://github.com/dufferzafar/src2tex/releases/download/v1/bitcoin.pdf), and it's going well.

**Comment by captn3m0** [comment]
I don't think I'd like the `wkhtmltopdf` approach, it would be slow and cumbersome compared to just `pandoc`. Let me do a first attempt and we'll see if it works.

I'm planning to split it into "decades" as books. So (1850-1930), (1930-1940), and so on. Planning to keep roughly 20-30 articles per book so it makes for a nice digest sized reading. There might be copyright issues with recent articles, so starting from the safe side.

`src2tex` looks nice. Only suggestion would be to link the filename header on each page to the index. Not all readers (esp on tables and readers like Kindle) make it easy to access the outline, and it would be helpful.

**Comment by captn3m0** [comment]
@dufferzafar Take a look at https://github.com/captn3m0/codechef/pull/8 when you get time. I wanted to try straight HTML (extracted from JSON) -> PDF but facing issues with latex.

The EPUB generation seems okay, needs a little more work though.
